# Generated by Django 4.0.4 on 2023-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='person',
            name='adres',
            field=models.CharField(help_text='Depremzedenin bulunduğu adres', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='isim',
            field=models.CharField(help_text='Depremzedenin ismi', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='sehir',
            field=models.CharField(default='Yok', help_text='Depremzedenin bulunduğu şehir', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(blank=True, help_text='Depremzedenin telefon numarası', max_length=13, null=True),
        ),
    ]
